export const useDemoData = () => {
  const getDemoMatches = () => [
    {
      id: 1,
      home: "Inter",
      away: "Milan",
      time: "20:45",
      date: new Date().toISOString(),
      homeOdds: 2.1,
      drawOdds: 3.4,
      awayOdds: 3.6,
      aiPrediction: "Casa",
      confidence: 78,
      stats: { homeForm: 85, awayForm: 72, h2h: "60% Casa" },
      status: "NS",
      venue: "San Siro",
      homeId: 505,
      awayId: 489,
      homeLogo: "https://media.api-sports.io/football/teams/505.png",
      awayLogo: "https://media.api-sports.io/football/teams/489.png",
    },
    {
      id: 2,
      home: "Juventus",
      away: "Napoli",
      time: "18:00",
      date: new Date().toISOString(),
      homeOdds: 2.25,
      drawOdds: 3.2,
      awayOdds: 3.3,
      aiPrediction: "X",
      confidence: 65,
      stats: { homeForm: 78, awayForm: 80, h2h: "45% Pareggi" },
      status: "NS",
      venue: "Allianz Stadium",
      homeId: 496,
      awayId: 492,
      homeLogo: "https://media.api-sports.io/football/teams/496.png",
      awayLogo: "https://media.api-sports.io/football/teams/492.png",
    },
    {
      id: 3,
      home: "Roma",
      away: "Lazio",
      time: "21:00",
      date: new Date().toISOString(),
      homeOdds: 2.4,
      drawOdds: 3.3,
      awayOdds: 3.0,
      aiPrediction: "Casa",
      confidence: 71,
      stats: { homeForm: 75, awayForm: 68, h2h: "55% Casa" },
      status: "NS",
      venue: "Olimpico",
      homeId: 497,
      awayId: 487,
      homeLogo: "https://media.api-sports.io/football/teams/497.png",
      awayLogo: "https://media.api-sports.io/football/teams/487.png",
    },
  ];

  const getDemoLiveMatches = () => [
    {
      id: 1,
      home: "PSG",
      away: "Lyon",
      homeScore: 2,
      awayScore: 1,
      time: 67,
      status: "2H",
    },
    {
      id: 2,
      home: "Bayern",
      away: "Dortmund",
      homeScore: 1,
      awayScore: 1,
      time: 82,
      status: "2H",
    },
    {
      id: 3,
      home: "Liverpool",
      away: "Chelsea",
      homeScore: 3,
      awayScore: 2,
      time: 45,
      status: "HT",
    },
  ];

  const getDemoH2hData = () => ({
    totalMatches: 10,
    team1Wins: 4,
    team2Wins: 3,
    draws: 3,
    team1WinPercentage: "40.0",
    team2WinPercentage: "30.0",
    drawPercentage: "30.0",
    avgGoals: "2.8",
    over25Percentage: "60.0",
    bttsPercentage: "70.0",
    lastMatches: [
      {
        date: "15/11/2024",
        homeTeam: "Inter",
        awayTeam: "Milan",
        homeScore: 2,
        awayScore: 1,
        winner: "home",
      },
      {
        date: "22/09/2024",
        homeTeam: "Milan",
        awayTeam: "Inter",
        homeScore: 1,
        awayScore: 1,
        winner: "draw",
      },
      {
        date: "10/05/2024",
        homeTeam: "Inter",
        awayTeam: "Milan",
        homeScore: 3,
        awayScore: 0,
        winner: "home",
      },
      {
        date: "18/02/2024",
        homeTeam: "Milan",
        awayTeam: "Inter",
        homeScore: 2,
        awayScore: 2,
        winner: "draw",
      },
      {
        date: "03/12/2023",
        homeTeam: "Inter",
        awayTeam: "Milan",
        homeScore: 1,
        awayScore: 2,
        winner: "away",
      },
    ],
  });

  return {
    getDemoMatches,
    getDemoLiveMatches,
    getDemoH2hData,
  };
};
