export const useDemoData = () => {
  const getDemoMatches = () => [
    {
      id: 1,
      home: "Inter",
      away: "Milan",
      time: "20:45",
      date: new Date().toISOString(),
      homeOdds: 2.1,
      drawOdds: 3.4,
      awayOdds: 3.6,
      aiPrediction: "Casa",
      confidence: 78,
      stats: { homeForm: 85, awayForm: 72, h2h: "60% Casa" },
      status: "NS",
      statusLong: "Not Started",
      venue: "San Siro",
      city: "Milano",
      referee: "Marco Guida",
      homeId: 505,
      awayId: 489,
      homeLogo: "https://media.api-sports.io/football/teams/505.png",
      awayLogo: "https://media.api-sports.io/football/teams/489.png",
      leagueName: "Serie A",
      leagueId: 135,
      leagueLogo: "https://media.api-sports.io/football/leagues/135.png",
    },
    {
      id: 2,
      home: "Juventus",
      away: "Napoli",
      time: "18:00",
      date: new Date().toISOString(),
      homeOdds: 2.25,
      drawOdds: 3.2,
      awayOdds: 3.3,
      aiPrediction: "X",
      confidence: 65,
      stats: { homeForm: 78, awayForm: 80, h2h: "45% Pareggi" },
      status: "NS",
      statusLong: "Not Started",
      venue: "Allianz Stadium",
      city: "Torino",
      referee: "Daniele Orsato",
      homeId: 496,
      awayId: 492,
      homeLogo: "https://media.api-sports.io/football/teams/496.png",
      awayLogo: "https://media.api-sports.io/football/teams/492.png",
      leagueName: "Serie A",
      leagueId: 135,
      leagueLogo: "https://media.api-sports.io/football/leagues/135.png",
    },
    {
      id: 3,
      home: "Roma",
      away: "Lazio",
      time: "21:00",
      date: new Date().toISOString(),
      homeOdds: 2.4,
      drawOdds: 3.3,
      awayOdds: 3.0,
      aiPrediction: "Casa",
      confidence: 71,
      stats: { homeForm: 75, awayForm: 68, h2h: "55% Casa" },
      status: "NS",
      statusLong: "Not Started",
      venue: "Stadio Olimpico",
      city: "Roma",
      referee: "Luca Pairetto",
      homeId: 497,
      awayId: 487,
      homeLogo: "https://media.api-sports.io/football/teams/497.png",
      awayLogo: "https://media.api-sports.io/football/teams/487.png",
      leagueName: "Serie A",
      leagueId: 135,
      leagueLogo: "https://media.api-sports.io/football/leagues/135.png",
    },
    {
      id: 4,
      home: "Atalanta",
      away: "Fiorentina",
      time: "15:00",
      date: new Date().toISOString(),
      homeOdds: 1.95,
      drawOdds: 3.5,
      awayOdds: 4.2,
      aiPrediction: "Casa",
      confidence: 82,
      stats: { homeForm: 88, awayForm: 65, h2h: "70% Casa" },
      status: "NS",
      statusLong: "Not Started",
      venue: "Gewiss Stadium",
      city: "Bergamo",
      referee: "Federico La Penna",
      homeId: 499,
      awayId: 502,
      homeLogo: "https://media.api-sports.io/football/teams/499.png",
      awayLogo: "https://media.api-sports.io/football/teams/502.png",
      leagueName: "Serie A",
      leagueId: 135,
      leagueLogo: "https://media.api-sports.io/football/leagues/135.png",
    },
  ];

  const getDemoLiveMatches = () => [
    {
      id: 101,
      home: "PSG",
      away: "Lyon",
      homeScore: 2,
      awayScore: 1,
      time: 67,
      status: "2H",
      statusLong: "Second Half",
      homeLogo: "https://media.api-sports.io/football/teams/85.png",
      awayLogo: "https://media.api-sports.io/football/teams/80.png",
      leagueName: "Ligue 1",
      leagueLogo: "https://media.api-sports.io/football/leagues/61.png",
    },
    {
      id: 102,
      home: "Bayern Munich",
      away: "Borussia Dortmund",
      homeScore: 1,
      awayScore: 1,
      time: 82,
      status: "2H",
      statusLong: "Second Half",
      homeLogo: "https://media.api-sports.io/football/teams/157.png",
      awayLogo: "https://media.api-sports.io/football/teams/165.png",
      leagueName: "Bundesliga",
      leagueLogo: "https://media.api-sports.io/football/leagues/78.png",
    },
    {
      id: 103,
      home: "Liverpool",
      away: "Chelsea",
      homeScore: 3,
      awayScore: 2,
      time: 45,
      status: "HT",
      statusLong: "Halftime",
      homeLogo: "https://media.api-sports.io/football/teams/40.png",
      awayLogo: "https://media.api-sports.io/football/teams/49.png",
      leagueName: "Premier League",
      leagueLogo: "https://media.api-sports.io/football/leagues/39.png",
    },
  ];

  const getDemoH2hData = () => ({
    totalMatches: 12,
    team1Wins: 5,
    team2Wins: 3,
    draws: 4,
    team1WinPercentage: "41.7",
    team2WinPercentage: "25.0",
    drawPercentage: "33.3",
    avgGoals: "2.9",
    over25Percentage: "66.7",
    bttsPercentage: "75.0",
    lastMatches: [
      {
        date: "15/11/2024",
        homeTeam: "Inter",
        awayTeam: "Milan",
        homeScore: 2,
        awayScore: 1,
        winner: "home",
      },
      {
        date: "22/09/2024",
        homeTeam: "Milan",
        awayTeam: "Inter",
        homeScore: 1,
        awayScore: 1,
        winner: "draw",
      },
      {
        date: "10/05/2024",
        homeTeam: "Inter",
        awayTeam: "Milan",
        homeScore: 3,
        awayScore: 0,
        winner: "home",
      },
      {
        date: "18/02/2024",
        homeTeam: "Milan",
        awayTeam: "Inter",
        homeScore: 2,
        awayScore: 2,
        winner: "draw",
      },
      {
        date: "03/12/2023",
        homeTeam: "Inter",
        awayTeam: "Milan",
        homeScore: 1,
        awayScore: 2,
        winner: "away",
      },
    ],
  });

  const getDemoStandings = () => [
    {
      rank: 1,
      team: {
        id: 505,
        name: "Inter",
        logo: "https://media.api-sports.io/football/teams/505.png",
      },
      points: 48,
      goalsDiff: 28,
      all: {
        played: 17,
        win: 15,
        draw: 3,
        lose: 0,
        goals: { for: 45, against: 17 },
      },
      form: "WWDWW",
    },
    {
      rank: 2,
      team: {
        id: 492,
        name: "Napoli",
        logo: "https://media.api-sports.io/football/teams/492.png",
      },
      points: 41,
      goalsDiff: 20,
      all: {
        played: 17,
        win: 12,
        draw: 5,
        lose: 0,
        goals: { for: 38, against: 18 },
      },
      form: "WDWDW",
    },
    {
      rank: 3,
      team: {
        id: 499,
        name: "Atalanta",
        logo: "https://media.api-sports.io/football/teams/499.png",
      },
      points: 40,
      goalsDiff: 24,
      all: {
        played: 17,
        win: 12,
        draw: 4,
        lose: 1,
        goals: { for: 46, against: 22 },
      },
      form: "WWLWW",
    },
    {
      rank: 4,
      team: {
        id: 496,
        name: "Juventus",
        logo: "https://media.api-sports.io/football/teams/496.png",
      },
      points: 38,
      goalsDiff: 18,
      all: {
        played: 17,
        win: 10,
        draw: 8,
        lose: 0,
        goals: { for: 35, against: 17 },
      },
      form: "DDWWD",
    },
    {
      rank: 5,
      team: {
        id: 489,
        name: "AC Milan",
        logo: "https://media.api-sports.io/football/teams/489.png",
      },
      points: 31,
      goalsDiff: 10,
      all: {
        played: 17,
        win: 9,
        draw: 4,
        lose: 4,
        goals: { for: 32, against: 22 },
      },
      form: "WLWLW",
    },
  ];

  return {
    getDemoMatches,
    getDemoLiveMatches,
    getDemoH2hData,
    getDemoStandings,
  };
};
